version: '3.8'

services:
  read:
    build: .
    container_name: read
    restart: unless-stopped
    ports:
      - "4321:8080"
    volumes:
      # 映射配置文件，方便直接修改
      - ./conf.yml:/app/conf.yml
      # 映射图片资源目录
      - ./png:/app/png
      # 映射数据库文件（针对 SQLite 模式）
      - ./read.db:/app/read.db
      # 映射存储目录（如果是本地上传的书籍）
      - ./storage:/app/storage
    environment:
      TZ: Asia/Shanghai
      # 如果需要通过环境变量覆盖配置，可以在此添加
      # 例如：DB_JDBCURL: jdbc:mysql://...
    networks:
      - read

networks:
  read:
    driver: bridge